baseurl = "https://iwensu0313.github.io/"
languageCode = "en-us"
title = "Iwen Su"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
publishDir = "../iwensu0313.github.io"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Iwen Su"
	description = "Ocean enthusiast &amp; data scientist"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/main.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Iwen**, <br> a scuba diver and data scientist, living in San Diego"
		# The icons will be shown if you enter your username
		twitter = "iwen_su"
		github = "iwensu0313"
		linkedin = "iwensu"

		copyright = [
			"&copy; Iwen Su"
		]


	[params.about]
		hide  = false
		title = "About"
		content = "I graduated from the Bren School of Environmental Science & Management in June 2018 with a specialization in Coastal and Marine Management. Over the last two years, I've worked on various data science and client-based projects in fisheries, aquaculture, and ocean health. Currently working on a dashboard to visualize CA aquaculture data. Feel free to reach out with any questions, my contact information is at the bottom of this page!"


	[params.portfolio]
		hide  = false
		title = "Featured Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
		  link = "https://sbcosap.org"
		  thumb = "thumbs/cosap.jpg"
		  title = "Web Design & Content Editor."
		  description = "Finalized content, improved layout and organization for [Offshore Mussel Farming](https://www.sbcosap.org/mussel-farming) pages, added relevant [resources](https://www.sbcosap.org/resources), and created subscriber functionality for [COSAP website](https://sbcosap.org)."
		
		[[params.portfolio.gallery]]
		  link = "https://iwensu.shinyapps.io/ca-aquaculture"
		  thumb = "thumbs/aqculture-data.jpg"
		  title = "Interactive Data Dashboard."
		  description = "Created a [CA Aquaculture Dashboard](https://iwensu.shinyapps.io/ca-aquaculture) for synthesizing and visualizing existing data from a variety of sources, including US Department of Agriculture and NOAA."
		
		[[params.portfolio.gallery]]
		  link = "https://iwensu.shinyapps.io/global-dashboard/"
		  thumb = "thumbs/shiny-mar.jpg"
		  title = "Interactive Data Dashboard."
		  description = "The [Data Exploration Dashboard](https://iwensu.shinyapps.io/global-dashboard/) I created for the OHI Project provides a quick glance into the data behind calculating global scores. Read about it in my [featured article](http://ohi-science.org/news/fellowship-expanding-mariculture)!"
		  
		[[params.portfolio.gallery]]
		  link = "https://ohi-science.github.io/globalfellows"
			thumb = "thumbs/ohi.jpg"
			title = "Ocean Health Research."
			description = "Calculated status of fisheries, mariculture, MPAs, and social progress for the 2018 [OHI Global Assessment](https://ohi-science.github.io/globalfellows) at NCEAS. Synthesized large datasets, communicated research."

		[[params.portfolio.gallery]]
			link = "https://sbmussels.weebly.com"
			thumb = "thumbs/gp.jpg"
			title = "Client-based Master's Thesis."
			description = "Investigated the [feasibility of seaweed aquaculture](https://sbmussels.weebly.com) in southern California for [Santa Barbara Mariculture](http://www.sbmariculture.com/) and the [Sustainable Aquaculture Research Center](http://sarc.bren.ucsb.edu/)."

		[[params.portfolio.gallery]]
		  link = "http://www.cagroundfish.org/"
			thumb = "thumbs/tnc.jpg"
			title = "Spatial Planning."
			description = "Streamlined marine spatial planning for the [CA Groundfish Collective](http://www.cagroundfish.org/) and TNC by implementing [SeaSketch](http://http://www.seasketch.org) as a cloud-based, planning tool."

	
	[params.recentposts]
		hide  = false
		title = "Presentations & Workshops"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = ""

		# This can be exact coordinates or a searchable address in google maps
		

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "du.iwensu@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10

[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0
